---

- name: Install IUS Community Project repository
  command: yum install -y https://centos7.iuscommunity.org/ius-release.rpm
  args:
    creates: /etc/yum.repos.d/ius.repo

- name: Install Python3 from IUS Community Project
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python36u
    - python36u-libs
    - python36u-devel
    - python36u-pip