---

- name: Hash password
  shell: "echo '{{ cntlm_config.password }}' | cntlm -H -d {{ cntlm_config.domain }} -u {{ cntlm_config.username }}"
  register: cntlm_hash_cmd

- set_fact:
    pass_ntlmv2: "{{ cntlm_hash_cmd.stdout_lines[3].split()[1] }}"

- name: Configure /etc/cntlm.conf
  template:
    src: cntlm.conf.j2
    dest: /etc/cntlm.conf
    mode: 0600
  notify: restart cntlmd