---

- name: Install CNTLM package
  block:
    - find:
        paths: "{{ cntlm_rpm_dir }}"
        patterns: "*.rpm"
      register: rpm_files
    - yum:
        name: "{{ rpm_files.files | map(attribute='path') | list}}"
        state: present

- name: Fix missing pid dir for cntlmd
  file:
    owner: cntlm
    group: cntlm
    path: /var/run/cntlm
    state: directory
    mode: 0755

- name: Add CNTLM profile script for defining proxies
  template:
    src: cntlm.sh.j2
    dest: /etc/profile.d/cntlm.sh
    mode: 0644

- name: Ensure CNTLM daemon is started at boot and running
  service:
    name: cntlmd
    state: started
    enabled: yes

- name: Configure CNTLM
  include: cntlm_config.yml
  when: cntlm_config is defined
