---

- hosts: all
  become: yes

  vars_prompt:
    - name: full_name
      prompt: "Full name"
      private: no
    - name: email
      prompt: "E-mail"
      private: no
    - name: username
      prompt: "User name"
      private: no
    - name: password
      prompt: "Password"
    - name: hostname
      prompt: "Hostname (host PC)"
      private: no

  tasks:

    - block:
      - name: Set Git user name
        git_config:
          name: user.name
          scope: global
          value: "{{ full_name }}"
      - name: Set Git user e-mail
        git_config:
          name: user.email
          scope: global
          value: "{{ email }}"
      become: no

# See roles/local_certs/files/README.txt for setting up trust stores first. Then enable this task.
    - include_role:
        name: local_certs
      when: false

    - include_role:
        name: docker
      vars:
        daemon:
          insecure-registries:
            - registry.local
          registry-mirrors:
            - https://registry.local

    - name: Encrypt password for Maven
      command: "mvn --encrypt-password {{ password }}"
      register: mvn_encrypted_password_cmd
      become: no

    - set_fact:
        mvn_encrypted_password: "{{ mvn_encrypted_password_cmd.stdout }}"

    - include_role:
        name: maven
        tasks_from: maven_config
      vars:
        user: vagrant
        settings:
          interactiveMode: "false"
          pluginGroups:
            - org.sonarsource.scanner.maven
          servers:
            - id: snapshots
              username: "{{ username }}"
              password: "{{ mvn_encrypted_password }}"
            - id: releases
              username: "{{ username }}"
              password: "{{ mvn_encrypted_password }}"
          mirrors:
            - id: nexus3
              mirrorOf: '*'
              url: https://nexus3.local/repository/maven-public/
          profiles:
            - id: sonar
              activation:
                activeByDefault: "true"
              properties:
                sonar.host.url: https://sonarqube.local/
                sonar.login: "{{ username }}"
                sonar.password: "{{ mvn_encrypted_password }}"
            - id: nexus3
              repositories:
                - id: central
                  url: https://nexus3.local/repository/maven-public/
                  releases:
                    enabled: "true"
                  snapshots:
                    enabled: "true"
              pluginRepositories:
                - id: central
                  url: https://nexus3.local/repository/maven-public/
                  releases:
                    enabled: "true"
                  snapshots:
                    enabled: "true"
          activeProfiles:
            - nexus3

    - include_role:
        name: node
      vars:
        npm_config:
          npm_registry: https://nexus3.local/repository/npm-all
          sass_binary_site: https://nexus3.local/repository/node-sass-binaries
          strict-ssl: "false"

    - include_role:
        name: instantclient
      vars:
        tnsnames:
          - name: ORCLCDB
            host: localhost
          - name: ORCLPDB1
            host: localhost

    - include_role:
        name: cntlm
      vars:
        cntlm_config:
          username: "{{ username }}"
          password: "{{ password }}"
          domain: local
          netbios_hostname: "{{ hostname }}"
          proxies:
            - proxy.local:8080
          no_proxy:
            - "*.local"
          user_agent: "Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/6.0)"
